name: Mein erster Check
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: node --check sum.js
      - run: node --check sum.test.js

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: node --test